### ISSUE TITLE
Implement root-to-tip regression and plotting

### ISSUE THREAD

**Issue by ArtPoon** [CoVaRR-NET/CoVaRRNet_pillar6notebook#3]
This appears to be generated outside of R, but it should be straight-forward to adapt existing code, e.g.:
https://github.com/brj1/node.dating
https://rdrr.io/github/emmanuelparadis/ape/src/R/rtt.R

**Comment by ArtPoon** [comment]
@murallcl can the ML tree be stored as a data object in this repo?

**Comment by murallcl** [comment]
yes I think so. I don't have a recent tree yet. I can give you the one in this repo now to play with. What size tree can your function handle? for the visualization we'll keep it to around 5000 but for the RTT, it should be larger (10,000 or so evenly downsampled over the whole canadian dataset). What do you think?

**Comment by ArtPoon** [comment]
won't know until I try, but 10K should be feasible...
will you be pushing the Newick file to this repo?
thanks

**Comment by murallcl** [comment]
yes! digging it up now.

**Comment by murallcl** [comment]
ok I added the tree in 'data needed' folder. It's a .treefile because it's from iqtree
I'll post the new one once I have it in the next day or two.

**Comment by ArtPoon** [comment]
Root-to-tip regression took 6 minutes on the tree you uploaded (thanks).  Here's a first draft figure:
![image](https://user-images.githubusercontent.com/1109328/150271669-4735e1ab-84ef-4ece-9f3d-735a5b571873.png)

**Comment by ArtPoon** [comment]
Couple things to note:
* some of those variant calls are totally bogus - for example that purple point sampled around June 2020 with high divergence is annotated as B.1.1.7 in the metadata, but that lineage was first described in the UK only several months afterwards
* the "belly" of points in the original plot is gone - not sure the rooted tree was being exported from TempEst properly.
* I'm not using ggplot2 for any of this because base R is good enough for most things

**Comment by ArtPoon** [comment]
I don't want the new code to disrupt the page (especially since RTT takes several minutes to compute), so I'm going to make a new branch `rtt` and push changes there.  We'll probably need to cache the RTT result and push that data file to the repo.

**Comment by ArtPoon** [comment]
Alternatively I can push my changes to my fork and then submit a PR.  @murallcl?

**Comment by murallcl** [comment]
wow fast! looks great. Can we get the linear regression values pasted somewhere on the plot? then it will update each time the plot is run and we don't have to change the text in the notebook each time we change the plot. 
- I think the best thing to do would be to add the rtt stuff  as a folder in "scripts" since in there we're compiling everything that takes too long to run inside the notebook or descriptions of how to run things outside of R. 
- Use the covarrnet version of the git because my @murallcl one was the original one that I made and then realized that it made more sense to have an organizational git for CoVaRR-Net, and then goofed up by forking it, and now it's just confusing. sorry!
- agreed about the variant calls, this issue keeps coming up and I think we should do some data cleaning on the Canadian dataset before using it, since it happening more often (not sure if that's true but it feels like it)
- for the record I have a love-hate (mostly hate) relationship with ggplot but after years of being made to use it with collaborators, I use it all the time, and still manage to curse at it from time to time. 
- Thanks again! and let's see what the others in the pillar think (and might want from this plot)

**Comment by ArtPoon** [comment]
* I think it makes more sense to store the regression values in the R instance where they can be embedded in other parts of the document - I'll add to demo
* I think it's perfectly reasonable to fork off your original repo - you shouldn't have to transfer ownership and it preserves provenance, i.e., you should get credit for starting the project
* this may be tricky because it may be caused by bad metadata - for example, some labs will randomize their sample collection dates
* the ggplot2 fandom drives me nuts.  There are some wonderful things being produced with that framework and it's inspired a community of users, but you don't *have* to use it.  No one should force either approach on anyone.
* what are you doing reviewing issues at two in the morning? - get some sleep! :-)
